export type { Person, PersonFormData } from './model/types/person'
export { personReducer, personActions } from './model/slice/personSlice'
export type { PersonSchema } from './model/types/personSchema'
export { getCloneTable } from './model/selectors/getCloneTable/getCloneTable'
export { AddNewForm } from './ui/addNewPerson/addNewForm'
